# Generated by Django 5.1.15 on 2026-09-13 08:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import common.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("server_sequence", models.BigIntegerField(db_index=True, default=0)),
                ("name", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[("EXPENSE", "Expense"), ("INCOME", "Income")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("icon", models.CharField(default="default", max_length=64)),
                (
                    "color",
                    models.CharField(
                        default="#808080",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid 6-digit hex code (e.g. #10B981).",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                ("is_system", models.BooleanField(db_index=True, default=False)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="subcategories",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
            },
        ),
    ]
