# Generated by Django 5.1.15 on 2026-09-13 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_system", True), ("user__isnull", True)),
                    models.Q(("is_system", False), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="chk_category_system_ownership",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(("color__regex", "^#[0-9A-Fa-f]{6}$")),
                name="chk_category_hex_color",
            ),
        ),
    ]
