# Generated by Django 5.1.15 on 2026-09-13 15:03

import common.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_device_push_token_device_push_token_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('RECURRING_DUE', 'Recurring Bill Due'), ('BUDGET_WARNING', 'Budget 80% Warning'), ('BUDGET_EXCEEDED', 'Budget 100% Exceeded'), ('REMOTE_SYNC_PING', 'Remote Data Sync Ping'), ('GENERAL', 'General Notification')], db_index=True, max_length=32)),
                ('stable_key', models.CharField(db_index=True, help_text='Deterministic key used for deduplication (e.g. rec_UUID_DATE)', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SENT', 'Delivered to FCM'), ('FAILED', 'Delivery Failed'), ('SIMULATED', 'Simulated in Dev/Test')], default='SENT', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='authentication.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notification_logs',
                'indexes': [models.Index(fields=['user', 'stable_key'], name='idx_notif_user_key'), models.Index(fields=['user', 'created_at'], name='idx_notif_user_created')],
            },
        ),
    ]
