# Generated by Django 5.1.15 on 2026-09-13 08:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import common.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("server_sequence", models.BigIntegerField(db_index=True, default=0)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        max_length=3,
                        validators=[django.core.validators.RegexValidator(regex="^[A-Z]{3}$")],
                    ),
                ),
                ("transaction_date", models.DateField(db_index=True)),
                ("payment_method", models.CharField(default="CASH", max_length=32)),
                ("payee", models.CharField(blank=True, max_length=100, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("client_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="expenses",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "db_table": "expenses",
            },
        ),
    ]
