# Generated by Django 5.1.15 on 2026-09-13 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0001_initial"),
        ("recurring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="recurring_expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_expenses",
                to="recurring.recurringexpense",
            ),
        ),
    ]
