# Generated by Django 5.1.15 on 2026-09-13 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["user", "-transaction_date"], name="idx_expenses_user_date"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["user", "category", "transaction_date"], name="idx_expenses_cat_spend"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["user", "server_sequence"], name="idx_expenses_sync_seq"),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="chk_expense_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__regex", "^[A-Z]{3}$")),
                name="chk_expense_currency_iso",
            ),
        ),
    ]
