# Generated by Django 5.1.15 on 2026-09-13 08:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import common.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("server_sequence", models.BigIntegerField(db_index=True, default=0)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        max_length=3,
                        validators=[django.core.validators.RegexValidator(regex="^[A-Z]{3}$")],
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("next_due_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="recurring_expenses",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring Expense",
                "verbose_name_plural": "Recurring Expenses",
                "db_table": "recurring_expenses",
            },
        ),
    ]
