# Generated by Django 5.1.15 on 2026-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='push_token',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='push_token_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
