# Generated by Django 5.1.15 on 2026-09-13 08:54

import django.core.validators
from django.db import migrations, models

import common.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("server_sequence", models.BigIntegerField(db_index=True, default=0)),
                ("period_start", models.DateField(db_index=True)),
                (
                    "limit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        max_length=3,
                        validators=[django.core.validators.RegexValidator(regex="^[A-Z]{3}$")],
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "db_table": "budgets",
            },
        ),
    ]
