# Generated by Django 5.1.15 on 2026-09-13 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budgets", "0001_initial"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="categories.category",
            ),
        ),
    ]
