# Generated by Django 5.1.15 on 2026-09-13 08:54

import django.db.models.deletion
from django.db import migrations, models

import common.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tombstone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_type", models.CharField(max_length=32)),
                ("entity_id", models.UUIDField(db_index=True, unique=True)),
                ("server_sequence", models.BigIntegerField(db_index=True)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tombstone",
                "verbose_name_plural": "Tombstones",
                "db_table": "tombstones",
            },
        ),
        migrations.CreateModel(
            name="SyncOperationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation_id", models.UUIDField(db_index=True, unique=True)),
                ("entity_type", models.CharField(max_length=32)),
                ("entity_id", models.UUIDField(db_index=True)),
                ("operation", models.CharField(max_length=10)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_operation_logs",
                        to="authentication.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Operation Log",
                "verbose_name_plural": "Sync Operation Logs",
                "db_table": "sync_operation_logs",
            },
        ),
    ]
