# Generated by Django 5.1.15 on 2026-09-13 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronization', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSyncSequence',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sync_sequence', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_sequence', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Sync Sequence',
                'verbose_name_plural': 'User Sync Sequences',
                'db_table': 'user_sync_sequences',
            },
        ),
        migrations.AddField(
            model_name='syncoperationlog',
            name='server_sequence',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='syncoperationlog',
            name='server_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='syncoperationlog',
            name='status',
            field=models.CharField(default='ACCEPTED', max_length=20),
        ),
    ]
